#!/usr/bin/env python3
"""TerminalClaw — regenerate a project's CLAUDE.md (its "agent brief").

Run by the `claude` wrapper (see agent.bashrc) on every launch, and by term.sh
when a session starts, so the brief always mirrors the tabs currently attached
to the project in projects.json.

Memory files are @-imported (Claude Code force-reads them at startup). Doc tabs
and the global Essentials/Credentials are listed as plain paths — the agent
knows they exist and reads them only if a task needs them (so secrets aren't
dumped into context up front).

Usage: gen_claude_md.py <project_id>
It writes <project dir>/CLAUDE.md and is a no-op for unknown projects / missing
dirs (so it never clobbers an unrelated folder).
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REGISTRY = os.path.join(HERE, "projects.json")
MEMORY_DIR = os.environ.get("HUB_MEMORY_DIR", os.path.join(HERE, "memory"))
MARKER = "AUTO-GENERATED by TerminalClaw"


def load_registry():
    with open(REGISTRY) as f:
        return json.load(f)


def resolve_memory(proj, basename):
    """A project memory entry is a .md basename, resolved against the project's
    own memory_dirs then the global MEMORY_DIR (same order as the dashboard)."""
    name = os.path.basename(basename or "")
    for d in list(proj.get("memory_dirs", [])) + [MEMORY_DIR]:
        p = os.path.join(d, name)
        if os.path.isfile(p):
            return p
    return None


def build(reg, proj):
    name = proj.get("name") or proj.get("id")
    dirpath = proj.get("dir") or ""
    L = []
    L.append("<!-- " + MARKER + " every time you launch `claude` in this project's")
    L.append("     terminal. Do NOT hand-edit — your changes are overwritten. Put durable")
    L.append("     project instructions in this project's memory file instead. -->")
    L.append("")
    L.append("# {} — project agent".format(name))
    L.append("")
    L.append("You are the agent for the **{}** project, working in `{}`.".format(name, dirpath))
    L.append("Keep your focus on this project.")
    L.append("")

    # Read-first: project memory (force-loaded via @import)
    mem = [p for p in (resolve_memory(proj, f) for f in proj.get("memory", [])) if p]
    if mem:
        L.append("## Read this first — important")
        L.append("This is your project memory. Read it before doing anything else:")
        L.append("")
        for p in mem:
            L.append("@" + p)
        L.append("")

    # Also-attached: doc tabs + global Essentials/Credentials (listed, on-demand)
    extras = []
    for t in proj.get("tabs", []):
        fp = os.path.expanduser(t.get("file", "") or "")
        if fp:
            extras.append((t.get("label") or os.path.basename(fp), fp))
    for tab in ("essentials", "credentials"):
        for it in reg.get(tab, []):
            fp = os.path.expanduser(it.get("file", "") or "")
            if fp:
                lbl = "{}: {}".format(tab.capitalize(), it.get("label") or os.path.basename(fp))
                extras.append((lbl, fp))
    if extras:
        L.append("## Also attached (read only if relevant)")
        L.append("These reference docs are available on this box. Open one only when the")
        L.append("task actually needs it — don't load them all up front:")
        L.append("")
        for lbl, fp in extras:
            L.append("- **{}** — `{}`".format(lbl, fp))
        L.append("")

    return "\n".join(L) + "\n"


def main():
    if len(sys.argv) < 2:
        return 1
    pid = sys.argv[1]
    try:
        reg = load_registry()
    except Exception:
        return 1
    proj = next((p for p in reg.get("projects", []) if p.get("id") == pid), None)
    if not proj:
        return 0
    dirpath = proj.get("dir") or ""
    if not dirpath or not os.path.isdir(dirpath):
        return 0
    out = os.path.join(dirpath, "CLAUDE.md")
    # Safety: if a non-generated CLAUDE.md already exists, back it up once.
    if os.path.isfile(out):
        try:
            with open(out, encoding="utf-8", errors="replace") as fh:
                head = fh.read(400)
            if MARKER not in head and not os.path.exists(out + ".preclaw"):
                os.replace(out, out + ".preclaw")
        except OSError:
            pass
    tmp = out + ".tmp"
    try:
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(build(reg, proj))
        os.replace(tmp, out)
    except OSError:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
